version: "3.8"
services:
  postgres:
    image: postgres:15.5
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=spinanda
    volumes:
      - ./docker/postgres/data:/var/lib/postgres/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql #Mounting a script to install extension in order to work with uuidv1 as primary key
    ports:
      - "5432:5432"

volumes:
  postgres:
